
import { Inter } from 'next/font/google'
import './globals.css'
import FirstNav from './component/FirstNav'
import Footer from './component/Footer'
import Providers from './component/Providers'
import { ClerkProvider } from '@clerk/nextjs'






const inter = Inter({ subsets: ['latin'] })

 export const metadata = {
 
  title: 'SKIMS | Solutions For Every Body',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (

    <ClerkProvider>
         <html lang="en">
          <head>
          <link rel="icon" href="/small.png" sizes="any" />
          </head>
      <body className=''>
      
      <Providers>
      <FirstNav/>
      <main className='relative overflow-hidden' >
       {children}
       </main>
       <Footer/>
      </Providers>
  
     </body>
    </html>
    </ClerkProvider>
  
  )
}
